# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b45d598495f0ef662829df0c2f37d321eb71e57d54e2fa33133b3a71471d4da79705a15b000414ab7459975aeace069c0ae4dc89e963264f1a779ec3d41b486

test:
  secret_key_base: 9ffa5a1162886806448bc4c86c63573c209ac0696a86ff4b4d999e761e98149001a38b40d5e474e2e828ea35c682c04a194d08cb83d16e7c387c9c242bc79d13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
